// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foamtec.qas.domain;

import com.foamtec.qas.domain.Rohs;
import com.foamtec.qas.domain.RohsDataOnDemand;
import com.foamtec.qas.domain.RohsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RohsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RohsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RohsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RohsIntegrationTest: @Transactional;
    
    @Autowired
    RohsDataOnDemand RohsIntegrationTest.dod;
    
    @Test
    public void RohsIntegrationTest.testCountRohses() {
        Assert.assertNotNull("Data on demand for 'Rohs' failed to initialize correctly", dod.getRandomRohs());
        long count = Rohs.countRohses();
        Assert.assertTrue("Counter for 'Rohs' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RohsIntegrationTest.testFindRohs() {
        Rohs obj = dod.getRandomRohs();
        Assert.assertNotNull("Data on demand for 'Rohs' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rohs' failed to provide an identifier", id);
        obj = Rohs.findRohs(id);
        Assert.assertNotNull("Find method for 'Rohs' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Rohs' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RohsIntegrationTest.testFindAllRohses() {
        Assert.assertNotNull("Data on demand for 'Rohs' failed to initialize correctly", dod.getRandomRohs());
        long count = Rohs.countRohses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Rohs', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Rohs> result = Rohs.findAllRohses();
        Assert.assertNotNull("Find all method for 'Rohs' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Rohs' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RohsIntegrationTest.testFindRohsEntries() {
        Assert.assertNotNull("Data on demand for 'Rohs' failed to initialize correctly", dod.getRandomRohs());
        long count = Rohs.countRohses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Rohs> result = Rohs.findRohsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Rohs' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Rohs' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RohsIntegrationTest.testFlush() {
        Rohs obj = dod.getRandomRohs();
        Assert.assertNotNull("Data on demand for 'Rohs' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rohs' failed to provide an identifier", id);
        obj = Rohs.findRohs(id);
        Assert.assertNotNull("Find method for 'Rohs' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRohs(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Rohs' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RohsIntegrationTest.testMergeUpdate() {
        Rohs obj = dod.getRandomRohs();
        Assert.assertNotNull("Data on demand for 'Rohs' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rohs' failed to provide an identifier", id);
        obj = Rohs.findRohs(id);
        boolean modified =  dod.modifyRohs(obj);
        Integer currentVersion = obj.getVersion();
        Rohs merged = (Rohs)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Rohs' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RohsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Rohs' failed to initialize correctly", dod.getRandomRohs());
        Rohs obj = dod.getNewTransientRohs(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Rohs' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Rohs' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Rohs' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RohsIntegrationTest.testRemove() {
        Rohs obj = dod.getRandomRohs();
        Assert.assertNotNull("Data on demand for 'Rohs' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rohs' failed to provide an identifier", id);
        obj = Rohs.findRohs(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Rohs' with identifier '" + id + "'", Rohs.findRohs(id));
    }
    
}
